/**
 * @file P2kTypes.h
 * @brief SDK type definitions for various data types used in the P2K platform.
 * @defgroup P2K_Types P2K Type Definitions
 * @{
 */

#ifndef P2K_SDK_DEVICE_LAYER_CALL_T_H
#define P2K_SDK_DEVICE_LAYER_CALL_T_H

#include "P2kT.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
	DL_SIG_CALL_CAUSE_NO_CAUSE,
	DL_SIG_CALL_CAUSE_CC_BUSY,
	DL_SIG_CALL_CAUSE_PARAMETER_ERROR,
	DL_SIG_CALL_CAUSE_INVALID_NUMBER,
	DL_SIG_CALL_CAUSE_OUTGOING_CALL_BARRED,
	DL_SIG_CALL_CAUSE_TOO_MANY_CALLS_ON_HOLD,
	DL_SIG_CALL_CAUSE_NORMAL,
	DL_SIG_CALL_CAUSE_INTERCEPT,
	DL_SIG_CALL_CAUSE_REORDER,
	DL_SIG_CALL_CAUSE_NO_SERVICE,
	DL_SIG_CALL_CAUSE_DROPPED,
	DL_SIG_CALL_CAUSE_SYSTEM_LOCKED,
	DL_SIG_CALL_CAUSE_NETWORK,
	DL_SIG_CALL_CAUSE_INVALID_CALL_ID,
	DL_SIG_CALL_CAUSE_NORMAL_CLEARING,
	DL_SIG_CALL_CAUSE_CALL_ALREADY_ANSWERED,
	DL_SIG_CALL_CAUSE_TOO_MANY_ACTIVE_CALLS,
	DL_SIG_CALL_CAUSE_UNASSIGNED_NUMBER,
	DL_SIG_CALL_CAUSE_NO_ROUTE_TO_DEST,
	DL_SIG_CALL_CAUSE_RESOURCE_UNAVAILABLE,
	DL_SIG_CALL_CAUSE_CALL_BARRED,
	DL_SIG_CALL_CAUSE_USER_BUSY,
	DL_SIG_CALL_CAUSE_NO_ANSWER,
	DL_SIG_CALL_CAUSE_CALL_REJECTED,
	DL_SIG_CALL_CAUSE_NUMBER_CHANGED,
	DL_SIG_CALL_CAUSE_DEST_OUT_OF_ORDER,
	DL_SIG_CALL_CAUSE_SIGNALING_ERROR,
	DL_SIG_CALL_CAUSE_NETWORK_ERROR,
	DL_SIG_CALL_CAUSE_NETWORK_BUSY,
	DL_SIG_CALL_CAUSE_NOT_SUBSCRIBED,
	DL_SIG_CALL_CAUSE_INCOMING_BARRED_IN_CUG,
	DL_SIG_CALL_CAUSE_SERVICE_UNAVAILABLE,
	DL_SIG_CALL_CAUSE_SERVICE_NOT_SUPPORTED,
	DL_SIG_CALL_CAUSE_PREPAY_LIMIT_REACHED,
	DL_SIG_CALL_CAUSE_USER_NOT_MEMBER_OF_CUG,
	DL_SIG_CALL_CAUSE_INCOMPATIBLE_DEST,
	DL_SIG_CALL_CAUSE_OUTSIDE_CALL_NOT_ALLOWED,
	DL_SIG_CALL_CAUSE_NO_CUG_SELECTED,
	DL_SIG_CALL_CAUSE_UNKNOWN_CUG_INDEX,
	DL_SIG_CALL_CAUSE_CUG_INDEX_INCOMPAT,
	DL_SIG_CALL_CAUSE_CUG_FAIL_UNSPECIFIED,
	DL_SIG_CALL_CAUSE_WEAK_SIGNAL,
	DL_SIG_CALL_CAUSE_RESTRICTED_LOCATION,
	DL_SIG_CALL_CAUSE_ACCESS_DENIED,
	DL_SIG_CALL_CAUSE_SIGNAL_FADED,
	DL_SIG_CALL_CAUSE_FEATURE_NOT_AVAILABLE,
	DL_SIG_CALL_CAUSE_WRONG_CALL_STATE,
	DL_SIG_CALL_CAUSE_SIGNALING_TIMEOUT,
	DL_SIG_CALL_CAUSE_MAX_MPTY_PARTICIPANTS_EXCEEDED,
	DL_SIG_CALL_CAUSE_SYSTEM_FAILURE,
	DL_SIG_CALL_CAUSE_DATA_MISSING,
	DL_SIG_CALL_CAUSE_BASIC_SERVICE_NOT_PROVISIONED,
	DL_SIG_CALL_CAUSE_ILLEGAL_SS_OPERATION,
	DL_SIG_CALL_CAUSE_SS_INCOMPATIBILITY,
	DL_SIG_CALL_CAUSE_SS_NOT_AVAILABLE,
	DL_SIG_CALL_CAUSE_SS_SUBSCRIPTION_VIOLATION,
	DL_SIG_CALL_CAUSE_INCORRECT_PASSWORD,
	DL_SIG_CALL_CAUSE_TOO_MANY_PASSWORD_ATTEMPTS,
	DL_SIG_CALL_CAUSE_PASSWORD_REGISTRATION_FAILURE,
	DL_SIG_CALL_CAUSE_ILLEGAL_EQUIPMENT,
	DL_SIG_CALL_CAUSE_UNKNOWN_SUBSCRIBER,
	DL_SIG_CALL_CAUSE_ILLEGAL_SUBSCRIBER,
	DL_SIG_CALL_CAUSE_ABSENT_SUBSCRIBER,
	DL_SIG_CALL_CAUSE_USSD_BUSY,
	DL_SIG_CALL_CAUSE_UNKNOWN_ALPHABET,
	DL_SIG_CALL_CAUSE_CANNOT_TRANSFER_MPTY_CALL,
	DL_SIG_CALL_CAUSE_BUSY_WITH_UNANSWERED_CALL,
	DL_SIG_CALL_CAUSE_FAILED_WITH_STATUS,
	DL_SIG_CALL_CAUSE_UNANSWERED_CALL_PENDING,
	DL_SIG_CALL_CAUSE_USSD_CANCELED,
	DL_SIG_CALL_CAUSE_FAST_RELEASE,
	DL_SIG_CALL_CAUSE_NOT_ALLOWED_BY_CC,
	DL_SIG_CALL_CAUSE_MODIFIED_TO_SS_BY_CC,
	DL_SIG_CALL_CAUSE_MODIFIED_TO_CALL_BY_CC,
	DL_SIG_CALL_CAUSE_CALL_MODIFIED_BY_CC,
	DL_SIG_CALL_CAUSE_POWER_DOWN
};
typedef UINT8 DL_SIG_CALL_CAUSE_T;

#ifdef __cplusplus
}
#endif

#endif  /* P2K_SDK_DEVICE_LAYER_CALLS_T_H */

/** @} */ /* end of P2K_Types */
