set(CMAKE_SYSTEM_NAME Windows)
set(TOOLCHAIN_ROOT "C:/Dev/MinGW")
set(TOOLCHAIN_PREFIX "${TOOLCHAIN_ROOT}/bin")
set(LIBRARIES_PREFIX "${TOOLCHAIN_ROOT}/lib")

set(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}/gcc.exe")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}/g++.exe")
set(CMAKE_RC_COMPILER "${TOOLCHAIN_PREFIX}/windres.exe")

set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_ROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
